apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer #Externo: Pide una IP pública
  selector:
    app: web #Busca los contenedores con la etiqueta 'app: web'
  ports:
    - protocol: TCP
      port: 80      #Puerto público (El que escribes en el navegador)
      targetPort: 5000 #Puerto interno del contenedor (El que usa Flask)
