name: pruebas de la aplicacion

on: 
  push:
    branches-ignore: ["main"] 

jobs:
  prueba:
    runs-on: ubuntu-latest
    permissions:
      security-events: write 
    steps:
      - name: Descargar c√≥digo
        uses: actions/checkout@v5

      - name: instalar python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: comprobar codigo
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint
